### ISSUE TITLE
Sound effects needed checklist

### ISSUE THREAD

**Issue by sardap** [sardap/walk-good-maybe#4]
**Sound Effects**
- [x] Jump sound
- [x] Flapping sound
- [x] Landing sound
- [x] Walking Sound
- [x] Poptart guy death sound
- [x] Pickup sound
- [x] health up sound
- [ ] Splash Sound

**Music**
- [ ] City 2nd track 
- [ ]  Beach 2nd track
- [ ] Title screen (Mix of both beach and city)
- [ ] Credits
